name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend_install:
    runs-on: self-hosted
    strategy:
      matrix:
        version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.version}}
      - run: |
          cd /var/www/PokerApp/_work/poker/poker/backend
          npm i
          

  frontend_install:
    runs-on: self-hosted
    strategy:
      matrix:
        version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.version}}
      - run: |
          
          cd /var/www/PokerApp/_work/poker/poker/frontend/
          npm i
  build:
      runs-on: self-hosted
      needs: frontend_install
      strategy:
        matrix:
          version: [ 18 ]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{matrix.version}}
          uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.version}}
        - run: |
            cd /var/www/PokerApp/_work/poker/poker/frontend/
            npm run build
