name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          cd /var/www/PokerApp/_work/poker/poker/backend
          npm i
          cd /var/www/PokerApp/_work/poker/poker/fronend/
          npm i
          npm run build
