name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  remove:
    runs-on: self-hosted
    steps:
      - run: rm -r /var/www/PokerApp/_work/poker

  backend_install:
    runs-on: self-hosted
    needs: remove
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd /var/www/PokerApp/_work/poker/poker/backend
          npm install
          

  frontend_install:
    runs-on: self-hosted
    needs: backend_install
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          
          cd /var/www/PokerApp/_work/poker/poker/frontend/
          npm i
  build:
      runs-on: self-hosted
      needs: frontend_install
      
      steps:
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: |
            cd /var/www/PokerApp/_work/poker/poker/frontend/
            sudo npm run build
  start:
      runs-on: self-hosted
      needs: build

      steps:
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: |
            cd /var/www/PokerApp/_work/poker/poker/backend/
            pm2 index.js --name "PokerApp"
