name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  npm_install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd /var/www/PokerApp/_work/poker/poker/backend
          npm install
          cd /var/www/PokerApp/_work/poker/poker/frontend
          npm install
          npm run build