name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm_istall:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies backend
        run: cd /var/www/PokerApp/_work/poker/poker/backend && npm install
      - name: Install dependencies frontend
        run: cd /var/www/PokerApp/_work/poker/poker/frontend && npm install
  build:
    needs: npm_istall
    runs-on: self-hosted
    steps:
      - name: Run Build
        run: cd /var/www/PokerApp/_work/poker/poker/frontend && npm run build
  start:
    needs: build
    runs-on: self-hosted
    steps:
      - name: start
      - run: |
          cd /var/www/PokerApp/_work/poker/poker/backend
          pm2 stop "PokerApp"
          pm2 start index.js --name "PokerApp"
          pm2 save
          sudo systemctl restart nginx